### ISSUE TITLE
Dear Owners, Timer On announcements

### ISSUE THREAD

**Issue by ZayBlockBugLine** [ZeezCode/MyAnnouncements#1]
Hey So I was wondering is the announcements automatic and what is there time span

**Comment by aidanscode** [comment]
The announcements automatically go through the list set in the config
You can set the delay between them in the config as well

**Comment by ZayBlockBugLine** [comment]
Can I have A Pic of the config file

**Comment by aidanscode** [comment]
It's on this GitHub https://github.com/ZeezCode/MyAnnouncements/blob/master/src/config.yml

**Comment by ZayBlockBugLine** [comment]
thanks
