### ISSUE TITLE
DEAR OWNER,

### ISSUE THREAD

**Issue by ZayBlockBugLine** [ZeezCode/MyAnnouncements#2]
Hey So I see You only have some downloads if i use this plugin on my server can u put my server on the plugin page kinda like a sponsor

**Comment by ZayBlockBugLine** [comment]
Like This:
COME SEE MY PLUGIN IN USE ON THIS SERVER!!!:
ZAYBLOCK.MYMCSERVER.ORG

**Comment by aidanscode** [comment]
The plugin doesn't have many downloads because I created and released it two days ago, but sure. Give me a logo for your server and I'll put it up.
Also, the issues page on GitHub is meant for issues with the plugin/its code. You can post stuff like this in the comments of the bukkit page.
